# Generated by Django 3.1.2 on 2020-11-10 14:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0002_auto_20201110_1144'),
    ]

    operations = [
        migrations.RenameField(
            model_name='turno',
            old_name='idpaciente',
            new_name='paciente',
        ),
        migrations.RenameField(
            model_name='turno',
            old_name='idprofesional',
            new_name='profesional',
        ),
    ]
