# Generated by Django 3.1.2 on 2020-11-11 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0004_auto_20201110_1209'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='turno',
            name='fechahora',
        ),
        migrations.AddField(
            model_name='turno',
            name='fecha',
            field=models.DateField(default=''),
        ),
        migrations.AddField(
            model_name='turno',
            name='hora',
            field=models.TimeField(default=''),
        ),
    ]
