# Generated by Django 3.1.2 on 2020-11-11 17:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0007_auto_20201111_1405'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Turno',
        ),
    ]
