# Generated by Django 3.1.2 on 2020-11-11 17:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0010_auto_20201111_1412'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Turno',
        ),
    ]
