# Generated by Django 3.1.2 on 2020-11-17 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0012_turno'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articulo',
            name='opcion1',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='articulo',
            name='opcion2',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='articulo',
            name='opcion3',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='articulo',
            name='precio',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10),
        ),
    ]
