# Generated by Django 3.1.2 on 2020-11-17 14:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0014_auto_20201117_1004'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedido',
            name='articulo',
        ),
        migrations.RemoveField(
            model_name='pedido',
            name='cantidad',
        ),
        migrations.CreateModel(
            name='ItemPedido',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField(blank=True)),
                ('precio', models.DecimalField(blank=True, decimal_places=2, max_digits=10)),
                ('estado', models.CharField(max_length=30)),
                ('articulo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sistema.articulo')),
            ],
        ),
        migrations.AddField(
            model_name='pedido',
            name='items',
            field=models.ManyToManyField(to='sistema.ItemPedido'),
        ),
    ]
