# Generated by Django 3.1.2 on 2020-11-18 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0016_pedido_fecha'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedido',
            name='items',
        ),
        migrations.RemoveField(
            model_name='pedido',
            name='paciente',
        ),
        migrations.RemoveField(
            model_name='articulo',
            name='opcion1',
        ),
        migrations.RemoveField(
            model_name='articulo',
            name='opcion2',
        ),
        migrations.RemoveField(
            model_name='articulo',
            name='opcion3',
        ),
        migrations.DeleteModel(
            name='ItemPedido',
        ),
        migrations.DeleteModel(
            name='Pedido',
        ),
    ]
