# Generated by Django 3.1.2 on 2020-11-18 14:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0018_itempedido_pedido'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedido',
            name='items',
        ),
        migrations.RemoveField(
            model_name='pedido',
            name='paciente',
        ),
        migrations.DeleteModel(
            name='ItemPedido',
        ),
        migrations.DeleteModel(
            name='Pedido',
        ),
    ]
