# Generated by Django 3.1.2 on 2020-11-18 14:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0020_itempedido_pedido'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pedido',
            old_name='precio',
            new_name='valor',
        ),
    ]
