# Generated by Django 3.1.2 on 2020-11-18 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0021_auto_20201118_1155'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='formapago',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
